"""Run restart and fork controls, committed before enqueue and audited on success."""

from datetime import UTC, datetime

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from mdcopilot_blog.api.deps import Principal
from mdcopilot_blog.db.models import AgentRun, Article, BlogRun, RunAttempt, TopicCandidateRecord
from mdcopilot_blog.domain.enums import RunStatus
from mdcopilot_blog.errors import ProblemError
from mdcopilot_blog.ids import uuid7
from mdcopilot_blog.services.audit import audit
from mdcopilot_blog.services.enqueue import enqueue_workflow, ensure_agent_enabled
from mdcopilot_blog.settings import Settings
from mdcopilot_blog.workflows.client import WorkflowClient
from mdcopilot_blog.workflows.names import (
    HUMAN_ACTION_WORKFLOWS,
    KNOWN_STEP_NAMES,
    QUEUE_INTERACTIVE,
    QUEUE_PIPELINE,
    WORKFLOW_CONTROL,
    WORKFLOW_DAILY_TRIGGER,
    WORKFLOW_DISCOVER_TOPICS,
    WORKFLOW_PRODUCE_ARTICLE,
    WORKFLOW_REGENERATE_TOPICS,
)

TERMINAL = {"SUCCEEDED", "FAILED", "CANCELLED"}


async def _require_idle(db: AsyncSession, run: BlogRun) -> None:
    active = await db.scalar(
        select(RunAttempt.id)
        .where(RunAttempt.run_id == run.id, RunAttempt.status.in_(["ENQUEUED", "RUNNING"]))
        .limit(1)
    )
    if active:
        raise ProblemError(409, "Run is busy", "wait for the active workflow to finish or cancel it first")


async def _protect_approved(db: AsyncSession, run: BlogRun, workflow_name: str) -> None:
    if workflow_name in {"publish_article", "recheck_article"}:
        return
    approved = await db.scalar(
        select(Article.id)
        .where(
            Article.run_id == run.id,
            Article.status.in_(["APPROVED", "SCHEDULED", "EXPORTED", "PUBLISHING", "PUBLISHED", "PUBLISH_FAILED"]),
        )
        .limit(1)
    )
    if approved:
        raise ProblemError(
            409, "Run cannot be restarted", "approved or published articles cannot be regenerated by restarting a run"
        )


async def restart_run(
    db: AsyncSession, client: WorkflowClient, *, run: BlogRun, principal: Principal, settings: Settings
) -> BlogRun:
    ensure_agent_enabled(settings)
    if run.status not in TERMINAL:
        raise ProblemError(409, "Run cannot be restarted", f"run is {run.status}")
    await _require_idle(db, run)
    article = await db.scalar(
        select(Article)
        .where(Article.run_id == run.id, Article.status.not_in(["REJECTED", "SUPERSEDED"]))
        .order_by(Article.created_at.desc())
        .limit(1)
    )
    if article and article.status in {"APPROVED", "SCHEDULED", "EXPORTED", "PUBLISHING", "PUBLISHED", "PUBLISH_FAILED"}:
        raise ProblemError(
            409, "Run cannot be restarted", "approved or published articles cannot be regenerated by restarting a run"
        )
    candidate_id = (
        article.candidate_id
        if article
        else await db.scalar(
            select(TopicCandidateRecord.id)
            .where(TopicCandidateRecord.run_id == run.id, TopicCandidateRecord.status == "SELECTED")
            .order_by(TopicCandidateRecord.selected_at.desc().nulls_last(), TopicCandidateRecord.created_at.desc())
            .limit(1)
        )
    )
    name = WORKFLOW_PRODUCE_ARTICLE if candidate_id else WORKFLOW_DISCOVER_TOPICS
    wid = (
        f"restart-produce-{run.id}-{candidate_id}-{uuid7()}" if candidate_id else f"restart-discover-{run.id}-{uuid7()}"
    )
    # The database field caps IDs at 128 bytes; UUID + prefix lengths fit exactly.
    previous, previous_finished, previous_error = run.status, run.finished_at, run.error
    run.status, run.finished_at, run.error = RunStatus.QUEUED.value, None, None
    count = await db.scalar(select(func.count()).select_from(RunAttempt).where(RunAttempt.run_id == run.id)) or 0
    attempt = RunAttempt(
        run_id=run.id, dbos_workflow_id=wid, workflow_name=name, attempt_no=count + 1, status="ENQUEUED"
    )
    db.add(attempt)
    await db.commit()
    try:
        await enqueue_workflow(
            client,
            workflow_name=name,
            queue_name=QUEUE_PIPELINE,
            workflow_id=wid,
            args=(str(run.id), str(candidate_id)) if candidate_id else (str(run.id),),
            timeout_seconds=(
                settings.production_timeout_minutes if candidate_id else settings.discovery_timeout_minutes
            )
            * 60,
        )
    except ProblemError:
        await db.refresh(attempt, with_for_update=True)
        await db.refresh(run, with_for_update=True)
        if attempt.status == "ENQUEUED":
            attempt.status, attempt.finished_at = "FAILED", datetime.now(UTC)
            attempt.error = {"stage": "enqueue", "message": "workflow service unavailable"}
            if run.status == "QUEUED":
                run.status, run.error, run.finished_at = previous, previous_error, previous_finished
        await db.commit()
        raise
    await audit(
        db,
        actor_user_id=principal.user_id,
        action="run.restart",
        entity_type="blog_run",
        entity_id=str(run.id),
        details={"workflow_id": wid, "workflow_name": name, "from_status": previous},
    )
    await db.commit()
    await db.refresh(run)
    return run


async def fork_step(
    db: AsyncSession,
    client: WorkflowClient,
    *,
    run: BlogRun,
    principal: Principal,
    step_name: str,
    retry: bool,
    settings: Settings,
) -> BlogRun:
    ensure_agent_enabled(settings)
    if step_name not in KNOWN_STEP_NAMES:
        raise ProblemError(404, "Step not found")
    pair = (
        await db.execute(
            select(AgentRun, RunAttempt)
            .join(RunAttempt, RunAttempt.id == AgentRun.attempt_id)
            .where(AgentRun.run_id == run.id, AgentRun.step_name == step_name)
            .order_by(RunAttempt.attempt_no.desc(), AgentRun.dbos_step_id.desc())
            .limit(1)
        )
    ).first()
    if pair is None:
        raise ProblemError(404, "Step not found")
    step, attempt = pair
    await _require_idle(db, run)
    await _protect_approved(db, run, attempt.workflow_name)
    newer = await db.scalar(
        select(RunAttempt.id)
        .where(
            RunAttempt.run_id == run.id,
            RunAttempt.workflow_name == attempt.workflow_name,
            RunAttempt.attempt_no > attempt.attempt_no,
        )
        .limit(1)
    )
    if newer:
        raise ProblemError(409, "Step cannot be restarted", "a newer attempt of this workflow exists")
    if retry and (attempt.status != "FAILED" or step.status != "FAILED"):
        raise ProblemError(409, "Step cannot be retried", "the latest attempt and selected step must have failed")
    if not retry and run.status not in TERMINAL:
        raise ProblemError(409, "Step cannot be restarted", f"run is {run.status}")
    if await client.status(attempt.dbos_workflow_id) is None:
        raise ProblemError(
            409, "Step cannot be retried" if retry else "Step cannot be restarted", "workflow history was pruned"
        )
    await db.commit()
    accepted = await enqueue_workflow(
        client,
        workflow_name=WORKFLOW_CONTROL,
        queue_name=QUEUE_INTERACTIVE,
        workflow_id=f"control-{uuid7()}",
        args=("fork", attempt.dbos_workflow_id, step_name),
        timeout_seconds=120,
    )
    await audit(
        db,
        actor_user_id=principal.user_id,
        action="run.step_retry" if retry else "run.step_restart",
        entity_type="blog_run",
        entity_id=str(run.id),
        details={
            "step_name": step_name,
            "workflow_id": attempt.dbos_workflow_id,
            "control_workflow_id": accepted.workflow_id,
        },
    )
    await db.commit()
    return run


async def resume_run(
    db: AsyncSession, client: WorkflowClient, *, run: BlogRun, principal: Principal, settings: Settings
) -> BlogRun:
    ensure_agent_enabled(settings)
    attempts = list(
        await db.scalars(
            select(RunAttempt)
            .where(RunAttempt.run_id == run.id, RunAttempt.status.in_(["ENQUEUED", "RUNNING"]))
            .order_by(RunAttempt.attempt_no.desc())
        )
    )
    for attempt in attempts:
        view = await client.describe(attempt.dbos_workflow_id)
        if (
            view is None
            or view.status not in {"PENDING", "ENQUEUED"}
            or not view.app_version
            or view.app_version == settings.app_version
        ):
            continue
        steps = await client.list_steps(attempt.dbos_workflow_id)
        await _protect_approved(db, run, attempt.workflow_name)
        start = (
            max(
                (step.function_id for step in steps if step.completed_at_epoch_ms is not None and step.error is None),
                default=0,
            )
            + 1
        )
        await db.commit()
        try:
            await client.cancel(attempt.dbos_workflow_id)
            attempt.status, attempt.finished_at = "CANCELLED", datetime.now(UTC)
            await db.commit()
            forked = await client.fork_from_function_id(
                attempt.dbos_workflow_id,
                start,
                queue_name=QUEUE_PIPELINE
                if attempt.workflow_name in {WORKFLOW_DISCOVER_TOPICS, WORKFLOW_PRODUCE_ARTICLE, WORKFLOW_DAILY_TRIGGER}
                else QUEUE_INTERACTIVE,
                timeout_seconds=(
                    settings.discovery_timeout_minutes
                    if attempt.workflow_name in {WORKFLOW_DISCOVER_TOPICS, WORKFLOW_REGENERATE_TOPICS}
                    else settings.production_timeout_minutes
                )
                * 60,
            )
        except Exception as exc:
            if attempt.status == "CANCELLED" and attempt.workflow_name not in HUMAN_ACTION_WORKFLOWS:
                await db.refresh(run, with_for_update=True)
                if run.status not in TERMINAL:
                    run.status, run.finished_at = "FAILED", datetime.now(UTC)
                    run.error = {"stage": "resume", "message": "previous workflow cancelled; retry or restart the run"}
                    await db.commit()
            raise ProblemError(503, "Workflow service unavailable", "run was not resumed") from exc
        await audit(
            db,
            actor_user_id=principal.user_id,
            action="run.resume",
            entity_type="blog_run",
            entity_id=str(run.id),
            details={"workflow_id": attempt.dbos_workflow_id, "forked_workflow_id": forked, "start_step": start},
        )
        await db.commit()
        return run
    raise ProblemError(409, "Nothing to resume", "no interrupted workflow on an older application version")
