"""foundation: auth, settings, brand, pillars, runs, attempts, step runs, LLM calls, prompts, notifications

Revision ID: 0001
Revises:
Create Date: 2026-09-17 00:00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # manual: autogenerate never emits extensions. No vector columns exist yet; later phases add them.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_content_pillars",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "topics", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column(
            "weekdays", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_content_pillars")),
        sa.UniqueConstraint("key", name=op.f("uq_blog_content_pillars_key")),
        schema="app",
    )
    op.create_table(
        "blog_prompt_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "front_matter",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_prompt_versions")),
        sa.UniqueConstraint("name", "version", name="uq_blog_prompt_versions_name_version"),
        schema="app",
    )
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
        schema="app",
    )
    op.create_index("ix_login_attempts_created_at", "login_attempts", ["created_at"], unique=False, schema="app")
    op.create_index(op.f("ix_login_attempts_email"), "login_attempts", ["email"], unique=False, schema="app")
    op.create_index(op.f("ix_login_attempts_ip"), "login_attempts", ["ip"], unique=False, schema="app")
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        schema="app",
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["app.users.id"], name=op.f("fk_audit_log_actor_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        schema="app",
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False, schema="app")
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"], unique=False, schema="app")
    op.create_table(
        "blog_brand_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app.users.id"], name=op.f("fk_blog_brand_profiles_created_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_brand_profiles")),
        sa.UniqueConstraint("version", name=op.f("uq_blog_brand_profiles_version")),
        schema="app",
    )
    op.create_index(
        "uq_blog_brand_profiles_active",
        "blog_brand_profiles",
        ["is_active"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "blog_notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app.users.id"], name=op.f("fk_blog_notifications_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_notifications")),
        schema="app",
    )
    op.create_index(
        op.f("ix_blog_notifications_user_id"), "blog_notifications", ["user_id"], unique=False, schema="app"
    )
    op.create_table(
        "blog_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column(
            "params", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), server_default=sa.text("0"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app.users.id"], name=op.f("fk_blog_runs_created_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_runs")),
        schema="app",
    )
    op.create_index("ix_blog_runs_created_at", "blog_runs", ["created_at"], unique=False, schema="app")
    op.create_index(op.f("ix_blog_runs_run_date"), "blog_runs", ["run_date"], unique=False, schema="app")
    op.create_index(op.f("ix_blog_runs_status"), "blog_runs", ["status"], unique=False, schema="app")
    op.create_index(
        "uq_blog_runs_daily_date",
        "blog_runs",
        ["run_date"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("kind = 'daily'"),
    )
    op.create_table(
        "blog_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app.users.id"], name=op.f("fk_blog_settings_created_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_settings")),
        sa.UniqueConstraint("version", name=op.f("uq_blog_settings_version")),
        schema="app",
    )
    op.create_index(
        "uq_blog_settings_active",
        "blog_settings",
        ["is_active"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app.users.id"], name=op.f("fk_user_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_sessions_token_hash")),
        schema="app",
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False, schema="app")
    op.create_table(
        "blog_llm_calls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("article_id", sa.Uuid(), nullable=True),
        sa.Column("topic_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("dbos_workflow_id", sa.String(length=128), nullable=True),
        sa.Column("dbos_step_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("agent_name", sa.String(length=64), nullable=True),
        sa.Column("prompt_name", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.Integer(), nullable=True),
        sa.Column("prompt_sha", sa.String(length=64), nullable=True),
        sa.Column("provider_requested", sa.String(length=32), nullable=False),
        sa.Column("model_requested", sa.String(length=128), nullable=False),
        sa.Column("provider_served", sa.String(length=32), nullable=True),
        sa.Column("model_served", sa.String(length=128), nullable=True),
        sa.Column("fallback_from", sa.String(length=200), nullable=True),
        sa.Column("attempt_index", sa.Integer(), nullable=False),
        sa.Column(
            "params", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reasoning_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("search_actions", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_class", sa.String(length=200), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "usage_raw", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), server_default=sa.text("0"), nullable=False),
        sa.Column("price_version", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["app.blog_runs.id"], name=op.f("fk_blog_llm_calls_run_id_blog_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_llm_calls")),
        schema="app",
    )
    op.create_index("ix_blog_llm_calls_created_at", "blog_llm_calls", ["created_at"], unique=False, schema="app")
    op.create_index(
        "ix_blog_llm_calls_provider_model",
        "blog_llm_calls",
        ["provider_requested", "model_requested"],
        unique=False,
        schema="app",
    )
    op.create_index(op.f("ix_blog_llm_calls_run_id"), "blog_llm_calls", ["run_id"], unique=False, schema="app")
    op.create_table(
        "blog_run_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("dbos_workflow_id", sa.String(length=128), nullable=False),
        sa.Column("workflow_name", sa.String(length=128), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("forked_from_workflow_id", sa.String(length=128), nullable=True),
        sa.Column("start_step", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["app.blog_runs.id"], name=op.f("fk_blog_run_attempts_run_id_blog_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_run_attempts")),
        sa.UniqueConstraint("dbos_workflow_id", name=op.f("uq_blog_run_attempts_dbos_workflow_id")),
        schema="app",
    )
    op.create_index(op.f("ix_blog_run_attempts_run_id"), "blog_run_attempts", ["run_id"], unique=False, schema="app")
    op.create_table(
        "blog_agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("dbos_workflow_id", sa.String(length=128), nullable=False),
        sa.Column("dbos_step_id", sa.Integer(), nullable=False),
        sa.Column("step_name", sa.String(length=128), nullable=False),
        sa.Column("agent_name", sa.String(length=64), nullable=True),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("prompt_name", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("tries", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "sources_used",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["app.blog_run_attempts.id"],
            name=op.f("fk_blog_agent_runs_attempt_id_blog_run_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["app.blog_runs.id"], name=op.f("fk_blog_agent_runs_run_id_blog_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_agent_runs")),
        sa.UniqueConstraint("dbos_workflow_id", "dbos_step_id", name="uq_blog_agent_runs_wf_step"),
        schema="app",
    )
    op.create_index("ix_blog_agent_runs_created_at", "blog_agent_runs", ["created_at"], unique=False, schema="app")
    op.create_index(op.f("ix_blog_agent_runs_run_id"), "blog_agent_runs", ["run_id"], unique=False, schema="app")
    op.create_index(op.f("ix_blog_agent_runs_status"), "blog_agent_runs", ["status"], unique=False, schema="app")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blog_agent_runs_status"), table_name="blog_agent_runs", schema="app")
    op.drop_index(op.f("ix_blog_agent_runs_run_id"), table_name="blog_agent_runs", schema="app")
    op.drop_index("ix_blog_agent_runs_created_at", table_name="blog_agent_runs", schema="app")
    op.drop_table("blog_agent_runs", schema="app")
    op.drop_index(op.f("ix_blog_run_attempts_run_id"), table_name="blog_run_attempts", schema="app")
    op.drop_table("blog_run_attempts", schema="app")
    op.drop_index(op.f("ix_blog_llm_calls_run_id"), table_name="blog_llm_calls", schema="app")
    op.drop_index("ix_blog_llm_calls_provider_model", table_name="blog_llm_calls", schema="app")
    op.drop_index("ix_blog_llm_calls_created_at", table_name="blog_llm_calls", schema="app")
    op.drop_table("blog_llm_calls", schema="app")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions", schema="app")
    op.drop_table("user_sessions", schema="app")
    op.drop_index(
        "uq_blog_settings_active", table_name="blog_settings", schema="app", postgresql_where=sa.text("is_active")
    )
    op.drop_table("blog_settings", schema="app")
    op.drop_index(
        "uq_blog_runs_daily_date", table_name="blog_runs", schema="app", postgresql_where=sa.text("kind = 'daily'")
    )
    op.drop_index(op.f("ix_blog_runs_status"), table_name="blog_runs", schema="app")
    op.drop_index(op.f("ix_blog_runs_run_date"), table_name="blog_runs", schema="app")
    op.drop_index("ix_blog_runs_created_at", table_name="blog_runs", schema="app")
    op.drop_table("blog_runs", schema="app")
    op.drop_index(op.f("ix_blog_notifications_user_id"), table_name="blog_notifications", schema="app")
    op.drop_table("blog_notifications", schema="app")
    op.drop_index(
        "uq_blog_brand_profiles_active",
        table_name="blog_brand_profiles",
        schema="app",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("blog_brand_profiles", schema="app")
    op.drop_index("ix_audit_log_created_at", table_name="audit_log", schema="app")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log", schema="app")
    op.drop_table("audit_log", schema="app")
    op.drop_table("users", schema="app")
    op.drop_index(op.f("ix_login_attempts_ip"), table_name="login_attempts", schema="app")
    op.drop_index(op.f("ix_login_attempts_email"), table_name="login_attempts", schema="app")
    op.drop_index("ix_login_attempts_created_at", table_name="login_attempts", schema="app")
    op.drop_table("login_attempts", schema="app")
    op.drop_table("blog_prompt_versions", schema="app")
    op.drop_table("blog_content_pillars", schema="app")
    # ### end Alembic commands ###
    # manual: the vector extension is left installed (it may be shared, and IF NOT EXISTS makes re-upgrade safe).
