"""blog schema

Revision ID: 0001
Revises:
Create Date: 2026-09-21 20:59:12.810269

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_brand_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_brand_profiles")),
        sa.UniqueConstraint("version", name=op.f("uq_blog_brand_profiles_version")),
    )
    op.create_index(
        "uq_blog_brand_profiles_active",
        "blog_brand_profiles",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "blog_content_pillars",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "topics", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column(
            "weekdays", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_content_pillars")),
        sa.UniqueConstraint("key", name=op.f("uq_blog_content_pillars_key")),
    )
    op.create_table(
        "blog_price_overrides",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("sku", sa.String(length=128), nullable=False),
        sa.Column("input_per_mtok", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("output_per_mtok", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("cache_read_per_mtok", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("per_1k_calls", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price_version", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "input_per_mtok IS NOT NULL OR output_per_mtok IS NOT NULL OR per_1k_calls IS NOT NULL",
            name=op.f("ck_blog_price_overrides_has_price"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_price_overrides")),
    )
    op.create_index(
        "uq_blog_price_overrides_provider_sku_effective_from",
        "blog_price_overrides",
        ["provider", "sku", "effective_from"],
        unique=True,
    )
    op.create_table(
        "blog_prompt_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "front_matter",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_prompt_versions")),
        sa.UniqueConstraint("name", "version", name="uq_blog_prompt_versions_name_version"),
    )
    op.create_table(
        "blog_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column(
            "params", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), server_default=sa.text("0"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_runs")),
    )
    op.create_index("ix_blog_runs_created_at", "blog_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_blog_runs_status"), "blog_runs", ["status"], unique=False)
    op.create_table(
        "blog_source_domains",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("publisher", sa.String(length=200), nullable=True),
        sa.Column("header_profile", sa.String(length=32), server_default=sa.text("'default'"), nullable=False),
        sa.Column("fetch_policy", sa.String(length=32), server_default=sa.text("'fetch'"), nullable=False),
        sa.Column("verification_allowlisted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "fetch_policy IN ('fetch','metadata_only','never')", name=op.f("ck_blog_source_domains_fetch_policy")
        ),
        sa.CheckConstraint("tier BETWEEN 1 AND 3", name=op.f("ck_blog_source_domains_tier")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_source_domains")),
        sa.UniqueConstraint("domain", name=op.f("uq_blog_source_domains_domain")),
    )
    op.create_table(
        "blog_llm_calls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("article_id", sa.Uuid(), nullable=True),
        sa.Column("topic_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("dbos_workflow_id", sa.String(length=128), nullable=True),
        sa.Column("dbos_step_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("agent_name", sa.String(length=64), nullable=True),
        sa.Column("prompt_name", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.Integer(), nullable=True),
        sa.Column("prompt_sha", sa.String(length=64), nullable=True),
        sa.Column("provider_requested", sa.String(length=32), nullable=False),
        sa.Column("model_requested", sa.String(length=128), nullable=False),
        sa.Column("provider_served", sa.String(length=32), nullable=True),
        sa.Column("model_served", sa.String(length=128), nullable=True),
        sa.Column("fallback_from", sa.String(length=200), nullable=True),
        sa.Column("attempt_index", sa.Integer(), nullable=False),
        sa.Column(
            "params", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reasoning_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("search_actions", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_class", sa.String(length=200), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "usage_raw", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), server_default=sa.text("0"), nullable=False),
        sa.Column("price_version", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["blog_runs.id"], name=op.f("fk_blog_llm_calls_run_id_blog_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_llm_calls")),
    )
    op.create_index("ix_blog_llm_calls_article_id", "blog_llm_calls", ["article_id"], unique=False)
    op.create_index("ix_blog_llm_calls_created_at", "blog_llm_calls", ["created_at"], unique=False)
    op.create_index(
        "ix_blog_llm_calls_provider_model", "blog_llm_calls", ["provider_requested", "model_requested"], unique=False
    )
    op.create_index(op.f("ix_blog_llm_calls_run_id"), "blog_llm_calls", ["run_id"], unique=False)
    op.create_index("ix_blog_llm_calls_topic_candidate_id", "blog_llm_calls", ["topic_candidate_id"], unique=False)
    op.create_table(
        "blog_research_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("pillar_key", sa.String(length=16), nullable=True),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column(
            "queries", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column(
            "signals", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column(
            "source_ids", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column(
            "phase_latency_ms",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "counts", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("dbos_workflow_id", sa.String(length=128), nullable=True),
        sa.Column("dbos_step_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["blog_runs.id"], name=op.f("fk_blog_research_runs_run_id_blog_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_research_runs")),
    )
    op.create_index("ix_blog_research_runs_created_at", "blog_research_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_blog_research_runs_kind"), "blog_research_runs", ["kind"], unique=False)
    op.create_index(op.f("ix_blog_research_runs_run_id"), "blog_research_runs", ["run_id"], unique=False)
    op.create_index(
        "uq_blog_research_runs_wf_step",
        "blog_research_runs",
        ["dbos_workflow_id", "dbos_step_id"],
        unique=True,
        postgresql_where=sa.text("dbos_workflow_id IS NOT NULL"),
    )
    op.create_table(
        "blog_run_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("dbos_workflow_id", sa.String(length=128), nullable=False),
        sa.Column("workflow_name", sa.String(length=128), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["blog_runs.id"], name=op.f("fk_blog_run_attempts_run_id_blog_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_run_attempts")),
        sa.UniqueConstraint("dbos_workflow_id", name=op.f("uq_blog_run_attempts_dbos_workflow_id")),
    )
    op.create_index(op.f("ix_blog_run_attempts_run_id"), "blog_run_attempts", ["run_id"], unique=False)
    op.create_table(
        "blog_topic_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("hook", sa.Text(), nullable=False),
        sa.Column("why_now", sa.Text(), nullable=False),
        sa.Column("thesis", sa.Text(), nullable=False),
        sa.Column("angle", sa.Text(), nullable=False),
        sa.Column("core_argument", sa.Text(), nullable=False),
        sa.Column("mdcopilot_connection", sa.Text(), nullable=False),
        sa.Column("target_audience", sa.Text(), nullable=False),
        sa.Column("pillar_key", sa.String(length=16), nullable=False),
        sa.Column(
            "examples", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("dbos_workflow_id", sa.String(length=128), nullable=True),
        sa.Column("dbos_step_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["blog_runs.id"], name=op.f("fk_blog_topic_candidates_run_id_blog_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_topic_candidates")),
    )
    op.create_index(op.f("ix_blog_topic_candidates_run_id"), "blog_topic_candidates", ["run_id"], unique=False)
    op.create_index(op.f("ix_blog_topic_candidates_status"), "blog_topic_candidates", ["status"], unique=False)
    op.create_index(
        "uq_blog_topic_candidates_wf_step",
        "blog_topic_candidates",
        ["dbos_workflow_id", "dbos_step_id"],
        unique=True,
        postgresql_where=sa.text("dbos_workflow_id IS NOT NULL"),
    )
    op.create_table(
        "blog_agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("dbos_workflow_id", sa.String(length=128), nullable=False),
        sa.Column("dbos_step_id", sa.Integer(), nullable=False),
        sa.Column("step_name", sa.String(length=128), nullable=False),
        sa.Column("agent_name", sa.String(length=64), nullable=True),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("prompt_name", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("tries", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "sources_used",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["blog_run_attempts.id"],
            name=op.f("fk_blog_agent_runs_attempt_id_blog_run_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["blog_runs.id"], name=op.f("fk_blog_agent_runs_run_id_blog_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_agent_runs")),
        sa.UniqueConstraint("dbos_workflow_id", "dbos_step_id", name="uq_blog_agent_runs_wf_step"),
    )
    op.create_index("ix_blog_agent_runs_created_at", "blog_agent_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_blog_agent_runs_run_id"), "blog_agent_runs", ["run_id"], unique=False)
    op.create_index(op.f("ix_blog_agent_runs_status"), "blog_agent_runs", ["status"], unique=False)
    op.create_table(
        "blog_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("publisher", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_source", sa.String(length=16), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("access_mode", sa.String(length=16), nullable=False),
        sa.Column("fetch_status", sa.String(length=32), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("word_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("text_snapshot", sa.Text(), nullable=True),
        sa.Column("is_preprint", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "external_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("discovered_via", sa.String(length=32), nullable=False),
        sa.Column("first_research_run_id", sa.Uuid(), nullable=True),
        sa.Column("relevance_score", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("tier BETWEEN 1 AND 3", name=op.f("ck_blog_sources_tier")),
        sa.ForeignKeyConstraint(
            ["first_research_run_id"],
            ["blog_research_runs.id"],
            name=op.f("fk_blog_sources_first_research_run_id_blog_research_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_sources")),
        sa.UniqueConstraint("url_hash", name=op.f("uq_blog_sources_url_hash")),
    )
    op.create_index(op.f("ix_blog_sources_domain"), "blog_sources", ["domain"], unique=False)
    op.create_index(op.f("ix_blog_sources_published_at"), "blog_sources", ["published_at"], unique=False)
    op.create_index(op.f("ix_blog_sources_tier"), "blog_sources", ["tier"], unique=False)
    op.create_table(
        "blog_topics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("pillar_key", sa.String(length=16), nullable=False),
        sa.Column("thesis", sa.Text(), nullable=False),
        sa.Column("angle", sa.Text(), nullable=False),
        sa.Column("core_argument", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["blog_topic_candidates.id"],
            name=op.f("fk_blog_topics_candidate_id_blog_topic_candidates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["blog_runs.id"], name=op.f("fk_blog_topics_run_id_blog_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_topics")),
        sa.UniqueConstraint("candidate_id", name=op.f("uq_blog_topics_candidate_id")),
    )
    op.create_table(
        "blog_articles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("pillar_key", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column(
            "tags", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("backend_blog_id", sa.String(length=64), nullable=True),
        sa.Column("draft_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["blog_topic_candidates.id"],
            name=op.f("fk_blog_articles_candidate_id_blog_topic_candidates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["blog_runs.id"], name=op.f("fk_blog_articles_run_id_blog_runs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["blog_topics.id"], name=op.f("fk_blog_articles_topic_id_blog_topics"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_articles")),
    )
    op.create_index("ix_blog_articles_created_at", "blog_articles", ["created_at"], unique=False)
    op.create_index(op.f("ix_blog_articles_run_id"), "blog_articles", ["run_id"], unique=False)
    op.create_index(op.f("ix_blog_articles_status"), "blog_articles", ["status"], unique=False)
    op.create_index(op.f("ix_blog_articles_topic_id"), "blog_articles", ["topic_id"], unique=False)
    op.create_index("uq_blog_articles_run_id_candidate_id", "blog_articles", ["run_id", "candidate_id"], unique=True)
    op.create_index(
        "uq_blog_articles_slug", "blog_articles", ["slug"], unique=True, postgresql_where=sa.text("slug IS NOT NULL")
    )
    op.create_table(
        "blog_research_packets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("research_run_id", sa.Uuid(), nullable=True),
        sa.Column("packet", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "source_ids", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("dbos_workflow_id", sa.String(length=128), nullable=True),
        sa.Column("dbos_step_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["blog_articles.id"],
            name=op.f("fk_blog_research_packets_article_id_blog_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["blog_research_runs.id"],
            name=op.f("fk_blog_research_packets_research_run_id_blog_research_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_research_packets")),
    )
    op.create_index(
        "uq_blog_research_packets_article_id_version", "blog_research_packets", ["article_id", "version"], unique=True
    )
    op.create_index(
        "uq_blog_research_packets_wf_step",
        "blog_research_packets",
        ["dbos_workflow_id", "dbos_step_id"],
        unique=True,
        postgresql_where=sa.text("dbos_workflow_id IS NOT NULL"),
    )
    op.create_table(
        "blog_article_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("parent_version_id", sa.Uuid(), nullable=True),
        sa.Column("change_kind", sa.String(length=32), nullable=False),
        sa.Column(
            "change_scope",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("title_options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pull_quote", sa.Text(), nullable=False),
        sa.Column("cta", sa.Text(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column(
            "citation_markers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "resolutions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("research_packet_id", sa.Uuid(), nullable=True),
        sa.Column("dbos_workflow_id", sa.String(length=128), nullable=True),
        sa.Column("dbos_step_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["blog_articles.id"],
            name=op.f("fk_blog_article_versions_article_id_blog_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["blog_article_versions.id"],
            name=op.f("fk_blog_article_versions_parent_version_id_blog_article_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["research_packet_id"],
            ["blog_research_packets.id"],
            name=op.f("fk_blog_article_versions_research_packet_id_blog_research_packets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_article_versions")),
    )
    op.create_index(
        "uq_blog_article_versions_article_id_version_no",
        "blog_article_versions",
        ["article_id", "version_no"],
        unique=True,
    )
    op.create_index(
        "uq_blog_article_versions_wf_step",
        "blog_article_versions",
        ["dbos_workflow_id", "dbos_step_id"],
        unique=True,
        postgresql_where=sa.text("dbos_workflow_id IS NOT NULL"),
    )
    op.create_table(
        "blog_article_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("marker", sa.String(length=8), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["blog_sources.id"],
            name=op.f("fk_blog_article_sources_source_id_blog_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["blog_article_versions.id"],
            name=op.f("fk_blog_article_sources_version_id_blog_article_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_article_sources")),
    )
    op.create_index(op.f("ix_blog_article_sources_source_id"), "blog_article_sources", ["source_id"], unique=False)
    op.create_index(
        "uq_blog_article_sources_version_id_marker", "blog_article_sources", ["version_id", "marker"], unique=True
    )
    op.create_index(
        "uq_blog_article_sources_version_id_source_id", "blog_article_sources", ["version_id", "source_id"], unique=True
    )
    op.create_table(
        "blog_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("independent_check", sa.Boolean(), nullable=True),
        sa.Column("writer_provider", sa.String(length=32), nullable=True),
        sa.Column("agent_provider", sa.String(length=32), nullable=True),
        sa.Column("agent_model", sa.String(length=128), nullable=True),
        sa.Column("gate_run_kind", sa.String(length=16), nullable=True),
        sa.Column("dbos_workflow_id", sa.String(length=128), nullable=True),
        sa.Column("dbos_step_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["blog_articles.id"],
            name=op.f("fk_blog_reviews_article_id_blog_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["blog_article_versions.id"],
            name=op.f("fk_blog_reviews_version_id_blog_article_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_reviews")),
    )
    op.create_index(op.f("ix_blog_reviews_article_id"), "blog_reviews", ["article_id"], unique=False)
    op.create_index("ix_blog_reviews_created_at", "blog_reviews", ["created_at"], unique=False)
    op.create_index("ix_blog_reviews_version_id_kind", "blog_reviews", ["version_id", "kind"], unique=False)
    op.create_index(
        "uq_blog_reviews_wf_step_kind",
        "blog_reviews",
        ["dbos_workflow_id", "dbos_step_id", "kind"],
        unique=True,
        postgresql_where=sa.text("dbos_workflow_id IS NOT NULL"),
    )
    op.create_table(
        "blog_version_seo",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("seo", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("social", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("dbos_workflow_id", sa.String(length=128), nullable=True),
        sa.Column("dbos_step_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["blog_article_versions.id"],
            name=op.f("fk_blog_version_seo_version_id_blog_article_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_version_seo")),
    )
    op.create_index(op.f("ix_blog_version_seo_version_id"), "blog_version_seo", ["version_id"], unique=False)
    op.create_index(
        "uq_blog_version_seo_wf_step",
        "blog_version_seo",
        ["dbos_workflow_id", "dbos_step_id"],
        unique=True,
        postgresql_where=sa.text("dbos_workflow_id IS NOT NULL"),
    )
    op.create_table(
        "blog_claim_checks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("review_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("importance", sa.String(length=16), nullable=False),
        sa.Column("section_key", sa.String(length=64), nullable=False),
        sa.Column("sentence_index", sa.Integer(), nullable=False),
        sa.Column("span", sa.Text(), nullable=False),
        sa.Column(
            "citation_markers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("recommended_revision", sa.Text(), nullable=True),
        sa.Column(
            "verification_source_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["blog_reviews.id"],
            name=op.f("fk_blog_claim_checks_review_id_blog_reviews"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["blog_sources.id"],
            name=op.f("fk_blog_claim_checks_source_id_blog_sources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["blog_article_versions.id"],
            name=op.f("fk_blog_claim_checks_version_id_blog_article_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_claim_checks")),
    )
    op.create_index(op.f("ix_blog_claim_checks_review_id"), "blog_claim_checks", ["review_id"], unique=False)
    op.create_index("ix_blog_claim_checks_version_id_kind", "blog_claim_checks", ["version_id", "kind"], unique=False)
    op.create_index(
        "uq_blog_claim_checks_review_id_position", "blog_claim_checks", ["review_id", "position"], unique=True
    )
    # ### end Alembic commands ###
    # Circular references, added once both tables exist (the models mark them use_alter).
    op.create_foreign_key(
        op.f("fk_blog_research_runs_article_id_blog_articles"),
        "blog_research_runs",
        "blog_articles",
        ["article_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_blog_articles_current_version_id_blog_article_versions"),
        "blog_articles",
        "blog_article_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # Article versions are immutable: a change is a new version row (autogenerate never emits this).
    op.execute(
        "CREATE FUNCTION blog_article_versions_block_update() RETURNS trigger LANGUAGE plpgsql AS $$\n"
        "BEGIN\n"
        "  RAISE EXCEPTION 'blog_article_versions rows are immutable' USING ERRCODE = 'restrict_violation';\n"
        "END $$"
    )
    op.execute(
        "CREATE TRIGGER trg_blog_article_versions_block_update BEFORE UPDATE ON blog_article_versions\n"
        "  FOR EACH ROW EXECUTE FUNCTION blog_article_versions_block_update()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_blog_article_versions_block_update ON blog_article_versions")
    op.execute("DROP FUNCTION IF EXISTS blog_article_versions_block_update()")
    op.drop_constraint(
        op.f("fk_blog_articles_current_version_id_blog_article_versions"), "blog_articles", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_blog_research_runs_article_id_blog_articles"), "blog_research_runs", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_blog_claim_checks_review_id_position", table_name="blog_claim_checks")
    op.drop_index("ix_blog_claim_checks_version_id_kind", table_name="blog_claim_checks")
    op.drop_index(op.f("ix_blog_claim_checks_review_id"), table_name="blog_claim_checks")
    op.drop_table("blog_claim_checks")
    op.drop_index(
        "uq_blog_version_seo_wf_step",
        table_name="blog_version_seo",
        postgresql_where=sa.text("dbos_workflow_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_blog_version_seo_version_id"), table_name="blog_version_seo")
    op.drop_table("blog_version_seo")
    op.drop_index(
        "uq_blog_reviews_wf_step_kind",
        table_name="blog_reviews",
        postgresql_where=sa.text("dbos_workflow_id IS NOT NULL"),
    )
    op.drop_index("ix_blog_reviews_version_id_kind", table_name="blog_reviews")
    op.drop_index("ix_blog_reviews_created_at", table_name="blog_reviews")
    op.drop_index(op.f("ix_blog_reviews_article_id"), table_name="blog_reviews")
    op.drop_table("blog_reviews")
    op.drop_index("uq_blog_article_sources_version_id_source_id", table_name="blog_article_sources")
    op.drop_index("uq_blog_article_sources_version_id_marker", table_name="blog_article_sources")
    op.drop_index(op.f("ix_blog_article_sources_source_id"), table_name="blog_article_sources")
    op.drop_table("blog_article_sources")
    op.drop_index(
        "uq_blog_article_versions_wf_step",
        table_name="blog_article_versions",
        postgresql_where=sa.text("dbos_workflow_id IS NOT NULL"),
    )
    op.drop_index("uq_blog_article_versions_article_id_version_no", table_name="blog_article_versions")
    op.drop_table("blog_article_versions")
    op.drop_index(
        "uq_blog_research_packets_wf_step",
        table_name="blog_research_packets",
        postgresql_where=sa.text("dbos_workflow_id IS NOT NULL"),
    )
    op.drop_index("uq_blog_research_packets_article_id_version", table_name="blog_research_packets")
    op.drop_table("blog_research_packets")
    op.drop_index("uq_blog_articles_slug", table_name="blog_articles", postgresql_where=sa.text("slug IS NOT NULL"))
    op.drop_index("uq_blog_articles_run_id_candidate_id", table_name="blog_articles")
    op.drop_index(op.f("ix_blog_articles_topic_id"), table_name="blog_articles")
    op.drop_index(op.f("ix_blog_articles_status"), table_name="blog_articles")
    op.drop_index(op.f("ix_blog_articles_run_id"), table_name="blog_articles")
    op.drop_index("ix_blog_articles_created_at", table_name="blog_articles")
    op.drop_table("blog_articles")
    op.drop_table("blog_topics")
    op.drop_index(op.f("ix_blog_sources_tier"), table_name="blog_sources")
    op.drop_index(op.f("ix_blog_sources_published_at"), table_name="blog_sources")
    op.drop_index(op.f("ix_blog_sources_domain"), table_name="blog_sources")
    op.drop_table("blog_sources")
    op.drop_index(op.f("ix_blog_agent_runs_status"), table_name="blog_agent_runs")
    op.drop_index(op.f("ix_blog_agent_runs_run_id"), table_name="blog_agent_runs")
    op.drop_index("ix_blog_agent_runs_created_at", table_name="blog_agent_runs")
    op.drop_table("blog_agent_runs")
    op.drop_index(
        "uq_blog_topic_candidates_wf_step",
        table_name="blog_topic_candidates",
        postgresql_where=sa.text("dbos_workflow_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_blog_topic_candidates_status"), table_name="blog_topic_candidates")
    op.drop_index(op.f("ix_blog_topic_candidates_run_id"), table_name="blog_topic_candidates")
    op.drop_table("blog_topic_candidates")
    op.drop_index(op.f("ix_blog_run_attempts_run_id"), table_name="blog_run_attempts")
    op.drop_table("blog_run_attempts")
    op.drop_index(
        "uq_blog_research_runs_wf_step",
        table_name="blog_research_runs",
        postgresql_where=sa.text("dbos_workflow_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_blog_research_runs_run_id"), table_name="blog_research_runs")
    op.drop_index(op.f("ix_blog_research_runs_kind"), table_name="blog_research_runs")
    op.drop_index("ix_blog_research_runs_created_at", table_name="blog_research_runs")
    op.drop_table("blog_research_runs")
    op.drop_index("ix_blog_llm_calls_topic_candidate_id", table_name="blog_llm_calls")
    op.drop_index(op.f("ix_blog_llm_calls_run_id"), table_name="blog_llm_calls")
    op.drop_index("ix_blog_llm_calls_provider_model", table_name="blog_llm_calls")
    op.drop_index("ix_blog_llm_calls_created_at", table_name="blog_llm_calls")
    op.drop_index("ix_blog_llm_calls_article_id", table_name="blog_llm_calls")
    op.drop_table("blog_llm_calls")
    op.drop_table("blog_source_domains")
    op.drop_index(op.f("ix_blog_runs_status"), table_name="blog_runs")
    op.drop_index("ix_blog_runs_created_at", table_name="blog_runs")
    op.drop_table("blog_runs")
    op.drop_table("blog_prompt_versions")
    op.drop_index("uq_blog_price_overrides_provider_sku_effective_from", table_name="blog_price_overrides")
    op.drop_table("blog_price_overrides")
    op.drop_table("blog_content_pillars")
    op.drop_index(
        "uq_blog_brand_profiles_active", table_name="blog_brand_profiles", postgresql_where=sa.text("is_active")
    )
    op.drop_table("blog_brand_profiles")
    # ### end Alembic commands ###
